export const userTemplate = {firstName:'', lastName: '', email:'', password:'', profileInfo: {
    sport: '',
    level: '',
    location:'',
    age:'',
    gender:'',
    aboutMe:'',
    sportsList:[],
    reviews:[],
    profileImageUrl:'',
    profileCompletePer:4,
    friendsList:[],
    completedEvents:[],
    availability: {
        Mon: { Mor: false, Aft: false, Eve: false },
        Tue: { Mor: false, Aft: false, Eve: false },
        Wed: { Mor: false, Aft: false, Eve: false },
        Thu: { Mor: false, Aft: false, Eve: false },
        Fri: { Mor: false, Aft: false, Eve: false },
        Sat: { Mor: false, Aft: false, Eve: false },
        Sun: { Mor: false, Aft: false, Eve: false },
    },
  },}