export const userTemplate = {firstName:'', lastName: '', email:'', password:'', profileInfo: {
    sport: '',
    level: '',
    location:'',
    age:'',
    gender:'',
    aboutMe:'',
    sportsList:[{sport:'',level:''}],
    reviews:'',
    activity:'',
    review:[{id:'',stars:'',text:''}],
    availibility: {
        Mon: { Morning: false, Afternoon: true, Evening: false },
        Tue: { Morning: false, Afternoon: false, Evening: false },
        Wed: { Morning: false, Afternoon: false, Evening: false },
        Thu: { Morning: true, Afternoon: false, Evening: false },
        Fri: { Morning: false, Afternoon: false, Evening: false },
        Sat: { Morning: false, Afternoon: false, Evening: false },
        Sun: { Morning: false, Afternoon: false, Evening: false },
    },
  },}