export const userTemplate = {firstName:'', lastName: '', email:'', password:'', profileInfo: {
    sport: '',
    level: '',
    location:'',
    age:'',
    gender:'',
    aboutMe:'',
    sportsList:[{sport:'',level:''}],
    reviews:'',
    activity:'',
    profileImageUrl:'',
    profileCompletePer:4,
    friendsList:[],
    review:[{id:'',stars:'',text:''}],
    availibility: {
        Mon: { Mor: false, Aft: true, Eve: false },
        Tue: { Mor: false, Aft: false, Eve: false },
        Wed: { Mor: false, Aft: false, Eve: false },
        Thu: { Mor: true, Aft: false, Eve: false },
        Fri: { Mor: false, Aft: false, Eve: false },
        Sat: { Mor: false, Aft: false, Eve: false },
        Sun: { Mor: false, Aft: false, Eve: false },
    },
  },}