export default {
  en: {
    profileTitle: 'Profile',
    profileAboutTab: 'About Me',
    profileSports: 'Sports',
    profileReviews: 'Reviews',
    profileActivity: 'Activity',
    ageProfile: 'Age',
    locationProfile: 'Location',
    genderProfile: 'Gender',
    sportProfile: 'Sport',
    myFreeTimeProfile: 'My free Time',
    completeProfileTitle: 'Complete your profile',
    profileCompletion: 'Profile Completion',
    profileCompletionCaption: 'Complete your profile to be able to join and create events',
    inputName: 'Input your first name',
    inputLastName: 'Input your last name',
    preferredSport: 'Choose your preferred sport',
    fillTimeSlots: 'Fill your available time slot(s)',
    chooseAge: 'Choose your age',
    setLocation: 'Set the location closest to you',
    chooseGender: 'Choose your gender',
    uploadPicture: 'Upload your profile picture',

    Yerevan: 'Yerevan',
    Aragatsotn: 'Aragatsotn',
    Ararat: 'Ararat',
    Armavir: 'Armavir',
    Gegharkunik: 'Gegharkunik',
    Kotayk: 'Kotayk',
    Lori: 'Lori',
    Shirak: 'Shirak',
    Syunik: 'Syunik',
    Tavush: 'Tavush',
    VayotsDzor: 'Vayots Dzor',

    cancelEditProfile: 'Cancel',
    saveEditProfile: 'Save',
    editProfile: 'Edit Profile',

    oneTimeSlotError: 'At least one time slot must be selected',
    lastNameError: 'Last name cannot be empty',
    firstNameError: 'First name cannot be empty',
    imageError: 'Please select a PNG or JPEG image.',

    personalInfo: 'PERSONAL INFO',
    firstNameEditProfile: 'First Name',
    lastNameEditProfile: 'Last Name',
    namePlaceHolder: 'Write your name...',
    lastNamePlaceHolder: 'Write your last name...',
    locationEditProfile: 'Location',
    ageAndGender: 'AGE AND GENDER',

    Male: 'Male',
    Female: 'Female',
    Other: 'Other',
  },

  am: {
    profileTitle: 'Պրոֆիլ',
    profileAboutTab: 'Իմ մասին',
    profileSports: 'Սպորտ',
    profileReviews: 'Կարծիքներ',
    profileActivity: 'Գործունեություն',
    ageProfile: 'Տարիք',
    locationProfile: 'Տեղակայություն',
    genderProfile: 'Սեռ',
    sportProfile: 'Սպորտ',
    myFreeTimeProfile: 'Իմ ազատ ժամանակը',
    completeProfileTitle: 'Լրացրեք ձեր պրոֆիլը',
    profileCompletion: 'Պրոֆիլի լրացում',
    profileCompletionCaption: 'Լրացրեք ձեր պրոֆիլը միջոցառումներին մասնակցելու և ստեղծելու համար',
    inputName: 'Մուտքագրեք ձեր անունը',
    inputLastName: 'Մուտքագրեք ձեր ազգանունը',
    preferredSport: 'Ընտրեք նախընտրած սպորտը',
    fillTimeSlots: 'Լրացրեք ձեր հասանելի ժամերը',
    chooseAge: 'Ընտրեք ձեր տարիքը',
    setLocation: 'Նշեք ձեզ ամենամոտ տարածքը',
    chooseGender: 'Ընտրեք ձեր սեռը',
    uploadPicture: 'Վերբեռնեք ձեր պրոֆիլի նկարը',

    Yerevan: 'Երևան',
    Aragatsotn: 'Արագածոտն',
    Ararat: 'Արարատ',
    Armavir: 'Արմավիր',
    Gegharkunik: 'Գեղարքունիք',
    Kotayk: 'Կոտայք',
    Lori: 'Լոռի',
    Shirak: 'Շիրակ',
    Syunik: 'Սյունիք',
    Tavush: 'Տավուշ',
    VayotsDzor: 'Վայոց Ձոր',

    cancelEditProfile: 'Չեղարկել',
    saveEditProfile: 'Պահպանել',
    editProfile: 'Խմբագրել պրոֆիլը',

    oneTimeSlotError: 'Պետք է ընտրել առնվազն մեկ ժամային հատված',
    lastNameError: 'Ազգանունը չի կարող դատարկ լինել',
    firstNameError: 'Անունը չի կարող դատարկ լինել',
    imageError: 'Խնդրում ենք ընտրել PNG կամ JPEG նկար։',

    personalInfo: 'ԱՆՁՆԱԿԱՆ ՏՎՅԱԼՆԵՐ',
    firstNameEditProfile: 'Անուն',
    lastNameEditProfile: 'Ազգանուն',
    namePlaceHolder: 'Գրեք ձեր անունը...',
    lastNamePlaceHolder: 'Գրեք ձեր ազգանունը...',
    locationEditProfile: 'Տեղակայություն',
    ageAndGender: 'ՏԱՐԻՔ ԵՎ ՍԵՌ',

    Male: 'Արական',
    Female: 'Իգական',
    Other: 'Այլ',
  },

  ru: {
    profileTitle: 'Профиль',
    profileAboutTab: 'Обо мне',
    profileSports: 'Спорт',
    profileReviews: 'Отзывы',
    profileActivity: 'Активность',
    ageProfile: 'Возраст',
    locationProfile: 'Местоположение',
    genderProfile: 'Пол',
    sportProfile: 'Спорт',
    myFreeTimeProfile: 'Моё свободное время',
    completeProfileTitle: 'Заполните профиль',
    profileCompletion: 'Заполнение профиля',
    profileCompletionCaption: 'Заполните профиль, чтобы участвовать и создавать мероприятия',
    inputName: 'Введите ваше имя',
    inputLastName: 'Введите вашу фамилию',
    preferredSport: 'Выберите предпочитаемый вид спорта',
    fillTimeSlots: 'Укажите доступное время',
    chooseAge: 'Выберите ваш возраст',
    setLocation: 'Укажите ближайшее к вам место',
    chooseGender: 'Выберите ваш пол',
    uploadPicture: 'Загрузите фото профиля',

    Yerevan: 'Ереван',
    Aragatsotn: 'Арагацотн',
    Ararat: 'Арарат',
    Armavir: 'Армавир',
    Gegharkunik: 'Гегаркуник',
    Kotayk: 'Котайк',
    Lori: 'Лори',
    Shirak: 'Ширак',
    Syunik: 'Сюник',
    Tavush: 'Тавуш',
    VayotsDzor: 'Вайоц Дзор',

    cancelEditProfile: 'Отмена',
    saveEditProfile: 'Сохранить',
    editProfile: 'Редактировать профиль',

    oneTimeSlotError: 'Необходимо выбрать хотя бы один временной слот',
    lastNameError: 'Фамилия не может быть пустой',
    firstNameError: 'Имя не может быть пустым',
    imageError: 'Пожалуйста, выберите изображение PNG или JPEG.',

    personalInfo: 'ЛИЧНАЯ ИНФОРМАЦИЯ',
    firstNameEditProfile: 'Имя',
    lastNameEditProfile: 'Фамилия',
    namePlaceHolder: 'Введите ваше имя...',
    lastNamePlaceHolder: 'Введите вашу фамилию...',
    locationEditProfile: 'Местоположение',
    ageAndGender: 'ВОЗРАСТ И ПОЛ',

    Male: 'Мужской',
    Female: 'Женский',
    Other: 'Другое',
  }
};
