export default {
    en: {
        //Sort
        SortGamesEvents: 'Sort Events',
        ClearSortFilterGames: 'Clear',
        CancelSortGamesButton: 'Cancel',
        DoneSortGamesButton: 'Done',
        SortGamesbyDate: 'Date',
        SortGamesbyPopularity: 'Popularity',
        SortGamesbyDistance: 'Distance',

        //Filter
        FilterEventsTitle: "Filter Events",
        FilterClearButton: "Clear",
        FilterSkillLevel: "Skill Level",
        FilterLocation: "Location",
        FilterDate: "Date",
        FilterTime: "Time",
        FilterLevelBeginner: "Beginner",
        FilterLevelIntermediate: "Intermediate",
        FilterLevelAdvanced: "Advanced",
        FilterCityYerevan: "Yerevan",
        FilterCityGyumri: "Gyumri",
        FilterCityVanadzor: "Vanadzor",
        FilterCityAbovyan: "Abovyan",
        FilterCityHrazdan: "Hrazdan",
        FilterCityDilijan: "Dilijan",
        FilterCityArtashat: "Artashat",
        FilterCityKapan: "Kapan",
        FilterCityGoris: "Goris",
        FilterDateToday: "Today",
        FilterDateThisWeek: "This Week",
        FilterDateThisMonth: "This Month",
        FilterTimeMorning: "Morning",
        FilterTimeAfternoon: "Afternoon",
        FilterTimeEvening: "Evening",
        FilterTimeLateNight: "Late Night",
        FilterCancelButton: "Cancel",
        FilterApplyButton: "Apply",

        //Games
        AllGames: 'All Games',
        MyGames: 'My Games',

        //GameEvents
        NoGameEvents: 'There are currently no events',
        ViewDetails: 'View Details',
        AskToJoin: 'Ask to Join',
        CourtBooked: "Booked",
        VerifiedUsersOnly: "Verified Users Only",

        //All Games
        Sports: 'Sports',
        Sort: 'Sort',
        Filter: 'Filter',
        CreateGame: 'Create a Game',

        //GameDetails
        GameDetailsPlayers: "Players",
        GameDetailsSport: "Sport",
        GameDetailsLevel: "Match level",
        GameDetailsLocation: "Location",
        GameDetailsDate: "Date & Time",
        GameDetailsChat: "Chat",
        GameDetailsNotes: "Notes",
        GameDetailsVerifiedOnly: "Verified users only",
        GameDetailsCourtBooked: "Booked",
        GameDetailsEligibility: 'Eligiblity',
        GameDetailsCourtNotBooked: 'Not booked',
        GameDetailsOpenEveryone: 'Open to Everyone',
        GameDetailsNoNotes: 'No additional notes are provided',
        GameHost: 'Game Host',
        GameNotFound: "Game not found",

        //Months
        Jan: 'Jan',
        Feb: 'Feb',
        Mar: 'Mar',
        Apr: 'Apr',
        May: 'May',
        Jun: 'Jun',
        Jul: 'Jul',
        Aug: 'Aug',
        Sep: 'Sep',
        Oct: 'Oct',
        Nov: 'Nov',
        Dec: 'Dec'

    },

    am: {
        // Sort
        SortGamesEvents: 'Դասակարգել միջոցառումները',
        ClearSortFilterGames: 'Մաքրել',
        CancelSortGamesButton: 'Չեղարկել',
        DoneSortGamesButton: 'Պատրաստ է',
        SortGamesbyDate: 'Ամսաթիվ',
        SortGamesbyPopularity: 'Հանրաճանաչություն',
        SortGamesbyDistance: 'Հեռավորություն',

        //Filter
        FilterEventsTitle: 'Ֆիլտրել միջոցառումները',
        FilterClearButton: 'Մաքրել',
        FilterSkillLevel: 'Մակարդակ',
        FilterLocation: 'Տեղակայություն',
        FilterDate: 'Ամսաթիվ',
        FilterTime: 'Ժամանակ',
        FilterLevelBeginner: 'Սկսնակ',
        FilterLevelIntermediate: 'Միջին',
        FilterLevelAdvanced: 'Բարձր',
        FilterCityYerevan: 'Երևան',
        FilterCityGyumri: 'Գյումրի',
        FilterCityVanadzor: 'Վանաձոր',
        FilterCityAbovyan: 'Աբովյան',
        FilterCityHrazdan: 'Հրազդան',
        FilterCityDilijan: 'Դիլիջան',
        FilterCityArtashat: 'Արտաշատ',
        FilterCityKapan: 'Կապան',
        FilterCityGoris: 'Գորիս',
        FilterDateToday: 'Այսօր',
        FilterDateThisWeek: 'Այս շաբաթ',
        FilterDateThisMonth: 'Այս ամիս',
        FilterTimeMorning: 'Առավոտ',
        FilterTimeAfternoon: 'Ցերեկ',
        FilterTimeEvening: 'Երեկո',
        FilterTimeLateNight: 'Ուշ գիշեր',
        FilterCancelButton: 'Չեղարկել',
        FilterApplyButton: 'Կիրառել',

        //Games
        AllGames: 'Բոլոր խաղերը',
        MyGames: 'Իմ խաղերը',

        //Game Events
        NoGameEvents: 'Ներկայումս միջոցառումներ չկան',
        ViewDetails: 'Դիտել մանրամասները',
        AskToJoin: 'Խնդրել միանալ',
        CourtBooked: "Դաշտը ամրագրված է",
        VerifiedUsersOnly: "Միայն հաստատված օգտատերերի համար",

        //All Games
        Sports: 'Սպորտ',
        Sort: 'Դասակարգում',
        Filter: 'Ֆիլտր',
        CreateGame: 'Ստեղծել խաղ',

        //GameDetails
        GameDetailsTitle: 'Օգտատիրոջ թենիսի խաղը',
        GameDetailsDateTime: 'Վաղը · 09:00',
        GameDetailsVerifiedOnly: 'Միայն հաստատված օգտատերերի համար',
        GameDetailsCourtBooked: 'Ամրագրված է',
        GameDetailsPlayers: 'Խաղացողներ',
        GameDetailsSport: 'Սպորտ',
        GameDetailsLevel: 'Խաղի մակարդակ',
        GameDetailsLevelValue: 'Վերին միջին, առաջադեմ',
        GameDetailsLocation: 'Տեղակայություն',
        GameDetailsClub: 'DSQ Gym & Health Club',
        GameDetailsAddress: 'Կոմիտասի պող. 12, Երևան, Հայաստան',
        GameDetailsDate: 'Ամսաթիվ և ժամ',
        GameDetailsDateRange: 'Վաղը · 09:00 – 11:00',
        GameDetailsNotes: 'Նշումներ',
        GameDetailsNotesText: 'Ընկերական մարզումային խաղ։ Բերեք ձեր սեփական ռակետը և ջուր։',
        GameDetailsChat: 'Չատ',
        GameDetailsAskToJoin: 'Դիմել միանալու համար',
        GameDetailsEligibility: 'Մասնակցության պայմաններ',
        GameDetailsCourtNotBooked: 'Ամրագրված չէ',
        GameDetailsOpenEveryone: 'Բաց բոլորի համար',
        GameDetailsNoNotes: 'Լրացուցիչ նշումներ չկան',
        GameHost: 'Խաղի կազմակերպիչ',
        GameNotFound: 'Խաղը չի գտնվել',
        //Months
        Jan: 'հնվ',
        Feb: 'փտր',
        Mar: 'մրտ',
        Apr: 'ապր',
        May: 'մայ',
        Jun: 'հնս',
        Jul: 'հլս',
        Aug: 'օգս',
        Sep: 'սեպ',
        Oct: 'հոկ',
        Nov: 'նոյ',
        Dec: 'դեկ'
  
},

ru: {
        // Sort
        SortGamesEvents: 'Сортировать мероприятия',
        ClearSortFilterGames: 'Очистить',
        CancelSortGamesButton: 'Отмена',
        DoneSortGamesButton: 'Готово',
        SortGamesbyDate: 'Дата',
        SortGamesbyPopularity: 'Популярность',
        SortGamesbyDistance: 'Расстояние',
        
        //Filter
        FilterEventsTitle: 'Фильтр мероприятий',
        FilterClearButton: 'Очистить',
        FilterSkillLevel: 'Уровень',
        FilterLocation: 'Местоположение',
        FilterDate: 'Дата',
        FilterTime: 'Время',
        FilterLevelBeginner: 'Новичок',
        FilterLevelIntermediate: 'Средний',
        FilterLevelAdvanced: 'Продвинутый',
        FilterCityYerevan: 'Ереван',
        FilterCityGyumri: 'Гюмри',
        FilterCityVanadzor: 'Ванадзор',
        FilterCityAbovyan: 'Абовян',
        FilterCityHrazdan: 'Раздан',
        FilterCityDilijan: 'Дилижан',
        FilterCityArtashat: 'Арташат',
        FilterCityKapan: 'Капан',
        FilterCityGoris: 'Горис',
        FilterDateToday: 'Сегодня',
        FilterDateThisWeek: 'На этой неделе',
        FilterDateThisMonth: 'В этом месяце',
        FilterTimeMorning: 'Утро',
        FilterTimeAfternoon: 'День',
        FilterTimeEvening: 'Вечер',
        FilterTimeLateNight: 'Поздняя ночь',
        FilterCancelButton: 'Отмена',
        FilterApplyButton: 'Применить',

        //Games
        AllGames: 'Все игры',
        MyGames: 'Мои игры',

        //Game Events
        NoGameEvents: 'В данный момент нет событий',
        ViewDetails: 'Подробнее',
        AskToJoin: 'Запросить участие',
        CourtBooked: "Площадка забронирована",
        VerifiedUsersOnly: "Только для подтверждённых пользователей",

        //ALL Games
        Sports: 'Виды спорта',
        Sort: 'Сортировать',
        Filter: 'Фильтр',
        CreateGame: 'Создать игру',

        //Game Details
        GameDetailsTitle: 'Теннисная игра пользователя',
        GameDetailsDateTime: 'Завтра · 09:00',
        GameDetailsVerifiedOnly: 'Только для подтверждённых пользователей',
        GameDetailsCourtBooked: 'Забронировано',
        GameDetailsPlayers: 'Игроки',
        GameDetailsSport: 'Спорт',
        GameDetailsLevel: 'Уровень матча',
        GameDetailsLevelValue: 'Выше среднего, продвинутый',
        GameDetailsLocation: 'Местоположение',
        GameDetailsClub: 'DSQ Gym & Health Club',
        GameDetailsAddress: 'пр-т Комитаса 12, Ереван, Армения',
        GameDetailsDate: 'Дата и время',
        GameDetailsDateRange: 'Завтра · 09:00 – 11:00',
        GameDetailsNotes: 'Заметки',
        GameDetailsNotesText: 'Дружеская тренировочная игра. Возьмите свою ракетку и воду.',
        GameDetailsChat: 'Чат',
        GameDetailsAskToJoin: 'Запросить участие',
        GameDetailsEligibility: 'Условия участия',
        GameDetailsCourtNotBooked: 'Не забронировано',
        GameDetailsOpenEveryone: 'Открыто для всех',
        GameDetailsNoNotes: 'Дополнительные заметки отсутствуют',
        GameHost: 'Организатор игры',
        GameNotFound: 'Игра не найдена',
        //months
        Jan: 'янв',
        Feb: 'фев',
        Mar: 'мар',
        Apr: 'апр',
        May: 'май',
        Jun: 'июн',
        Jul: 'июл',
        Aug: 'авг',
        Sep: 'сен',
        Oct: 'окт',
        Nov: 'ноя',
        Dec: 'дек'
}

};